config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#landing_page'
  resources :items do
    collection do
      get :my_items
      get :select_item
      post :remove_item
    end
    member do
      get :inc_quantity
      get :dec_quantity
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
end

app/controllers/items_controller.rb
require 'will_paginate/array' 
class ItemsController < ApplicationController
  before_action :set_item, only: [:edit, :show, :update, :destroy, :inc_quantity, :dec_quantity]
  before_action :authenticate_user!, except: [:index]
  before_action :verify_role!, except: [:index]
  after_action :check_quantity, only: [:create, :update, :dec_quantity]

  def index
    @items = Item.all
    @items = Item.paginate(page: params[:page], per_page: 10)
  end

  def my_items
    if current_user.present?
      @items = current_user.items
    else
      @items = Item.all
    end
    @items = @items.to_a
    @items = @items.paginate(page: params[:page], per_page: 10)
    #Item.paginate(page: params[:page], per_page: 30)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new item_params
    @item.user_id = current_user.id
    if @item.save
      redirect_to my_items_items_path
    else
      redirect_to my_items_items_path
    end
  end

  def edit
  end

  def update
    if @item.update item_params
      redirect_to my_items_items_path
    else
      redirect_to my_items_items_path
    end
  end

  def show

  end

  def select_item
    @items = current_user.items
  end

  def remove_item
    @item = (params[:id].to_i.to_s != params[:id]) ? Item.find_by(name: params[:id]) : Item.find(params[:id])
    @item.destroy
    redirect_to my_items_items_path
  end

  def destroy
    if @item.destroy
      redirect_to my_items_items_path
    else
      redirect_to my_items_items_path
    end
  end

  def inc_quantity
    @item.quantity = @item.quantity + 1
    @item.save
    redirect_to my_items_items_path
  end

  def dec_quantity
    @item.quantity = @item.quantity - 1
    @item.save
    redirect_to my_items_items_path
  end

  private

  def item_params
    params.require(:item).permit(:name, :quantity)
  end

  def set_item
    @item = Item.find params[:id]
  end

  def verify_role!
    if params[:id].present?
      @item = Item.find_by(name: params[:id]) if (params[:id].to_i.to_s != params[:id])
    end
    authorize @item || Item 
  end
  
  def check_quantity
    @item = Item.last if @item.nil?
    UserMailer.with(user: current_user, item: @item).inventory_email.deliver_now if @item.quantity == 0
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with model: @item do|f| %>
  <div class="center">
    <%= f.text_field :name, :cols => "30" %>
    <small class="form-text text-muted">Product Name</small>
  </div>
  <br>
  <div class="center">
    <%= f.text_field :quantity %>
    <small class="form-text text-muted center-text">Quantity</small>
  </div>
  <div class="row">
    <div class="col-sm-6 center"><%= link_to 'Back', my_items_items_path, class: 'app_button mt-4' %></div>
    <div class="col-sm-6 center"><input type="Submit" name="commit" value="Save" class="app_button mt-4" ></div>
  </div>
<% end %>

app/views/items/edit.html.erb
<div class="container">
  <div class="col-sm-2"></div>
    <div class="card">
      <div class="container">
        <%= render 'form', item: @item %>
      </div>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<div class="container">
  <div class="col-sm-2"></div>
    <div class="card">
      <div class="container">
        <div class="table_header">
          <div class="nudge_left"><h1>Products</h1></div>
          <table class="all_table">
            <thead>
              <tr>
                <th><%= 'Name' %></th>
                <th><%= 'Quantity' %></th>
                <th><%= 'User' %></th>
              </tr>
            </thead>

            <tbody>
              <% @items.each do |item| %>
                <tr>
                  <td><%= item.name %></td>
                  <td><%= item.quantity %></td>
                  <td><%= item.user.email %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <div class="row center"><%= will_paginate @items %></div>
        </div>
      </div>
    </div> 
  </div>
</div>

app/views/items/my_items.html.erb
<div class="container">
  <div class="col-sm-2"></div>
    <div class="card">
      <div class="container">
        <div class="table_header">
          <h1>My Products</h1>
          <table class="v1">
            <thead>
              <tr>
                <th><%= 'Name' %></th>
                <th><%= 'Quantity' %></th>
              </tr>
            </thead>

            <tbody>
              <% @items.each do |item| %>
                <tr>
                  <td><%= link_to "#{item.name}", edit_item_path(item), class: '' %></td>
                  <td><%= link_to "-", dec_quantity_item_path(item), class: '' %> <%= link_to "#{item.quantity}", edit_item_path(item), class: '' %> <%= link_to "+", inc_quantity_item_path(item), class: '' %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <div class="row center"><%= will_paginate @items %></div>
          <div class="row">
            <div class="col-sm-6 center"><%= link_to 'Add Product', new_item_path, :class => "app_button" %></div>
            <div class="col-sm-6 center"><%= link_to 'Remove Product', select_item_items_path, :class => "app_button" %></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<div class="container">
  <div class="col-sm-2"></div>
    <div class="card">
      <div class="container">
        <%= render 'form', item: @item %>
      </div>
    </div>
  </div>
</div>

app/views/items/select_item.html.erb
<div class="container">
  <div class="col-sm-2"></div>
    <div class="card">
      <div class="container">
        <div class="table_header">
          <h1>Select Products</h1>
          <%= form_tag(remove_item_items_path, method: 'POST') do -%>
            <%= select_tag :id, options_for_select(@items.pluck(:name)), { include_blank: true, required: true, class: 'form-control' } %>
            <small class="form-text text-muted">Product name</small>
            <div class="row">
              <div class="col-sm-6 center"><%= link_to 'Back', my_items_items_path, class: 'app_button mt-4' %></div>
              <div class="col-sm-6 center"><input type="submit" name="commit" value="Remove" class="app_button mt-4"></div>
            </div>
          <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>