config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#landing_page'
  resources :items do
    collection do
      get :my_items
      get :select_item
      post :remove_item
    end
    member do
      get :inc_quantity
      get :dec_quantity
    end
  end
end

app/views/layouts/_navigation.html.erb
<div class="user_links"%>
<% if current_user.nil? %>
  <div class="row">
    <div class='nav-item mr-2'><%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %></div>
    <div class='nav-item'><%= link_to 'Sign up', new_user_registration_path, class: "nav-link pr-0" %></div>
  </div>  
<% else %>
  <div class='nav-item'><%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %></div>
<% end %>
</div>

<div class="item_links">
  <div class="row">
    <div class="bigger"><%= link_to 'All Products', items_path, class: '' %></div>
    <div class="space"></div>
    <% if current_user.present? %><div class="bigger"><%= link_to 'My Products', my_items_items_path, class: '' %></div><% end %>
  </div>  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RadiateConsultingSkillTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
  </head>

  <body>
    <header id="mainNav">
      <%= render 'layouts/navigation' %>
    </header>
    <% if notice %>
      <div class="notice_class" id="notice_wrapper">
        <p class="notice"><%= notice %></p>
      </div>
    <% elsif alert %>
      <div class="notice_class" id="notice_wrapper">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <div class="body_div">
      <%= yield %>
    </div>
    <script type="text/javascript">
      window.addEventListener('load', function(event) {
        console.log("page loaded");
            setTimeout(function(){
            console.log("setTimeOut called");
            $('#notice_wrapper').fadeOut("slow", function() {
                $(this).remove();
            })
        }, 2500);
      });
    </script>
    <!-- JQuery -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  </body>
</html>